on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      should_release:
        description: "Run publish steps?"
        type: boolean
        required: true

name: release
jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          release-type: node
          package-name: test-release-please

      - name: Check out repository
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created || inputs.should_release }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      
      - run: npm ci
      - run: npm run bundle

      - run: node dist/upload--to-release.cjs bin/nlterm*
        if: ${{ steps.release.outputs.release_created || inputs.should_release }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: npm publish
        if: ${{ steps.release.outputs.release_created || inputs.should_release  }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
