on:
  push:
    branches:
      - main

name: release
jobs:

  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - uses: google-github-actions/release-please-action@v3
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          release-type: node
          package-name: test-release-please

      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: node dist/upload--to-release.cjs bin/nlterm*
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
